services:
  starwalker:
    build: .
    ports:
      - 1225:5000
    container_name: starwalker
    restart: on-failure
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M