services:
    greets-u:
      build: .
      ports:
        - 7101:8080
      container_name: greets-u
      restart: on-failure
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: 256M
